#
#Thu Jun 11 14:14:41 CST 2020
otp.domino.secret=erewqreqr876
cookie.domain=.vanke.com
openid.domino.secret=erewqre99988
email.domino.secret=erewqreqr888
token.expiration=30
#domino.secret=BTfa8F+H8wNejYEGhtuZSJuVTWOZ/tj8\=
domino.secret=BTfa8F+pHwNejYEGtAofuZSJTWOZ/t8B\=
