-- Local MySQL schema required by the unconfirmed-collection workbench.
CREATE TABLE IF NOT EXISTS eg_non_confirm_collection_sum (
    id BIGINT NOT NULL PRIMARY KEY,
    ebank_number TEXT NULL,
    collection_accounts_bank VARCHAR(200) NULL,
    collection_accounts_bank_no VARCHAR(200) NULL,
    ebank_serial_number TEXT NULL,
    create_by VARCHAR(64) NULL,
    create_time DATETIME NULL,
    update_by VARCHAR(64) NULL,
    update_time DATETIME NULL,
    del_flag CHAR(1) NULL DEFAULT '0',
    collection_accounts_bank_code VARCHAR(1000) NULL,
    business_ebank_number TEXT NULL,
    ebank_mapping_id BIGINT NULL,
    bank_amount DECIMAL(20,2) NULL DEFAULT 0,
    accounts_receivable DECIMAL(20,2) NULL DEFAULT 0,
    system_code VARCHAR(50) NULL,
    business_date DATETIME NULL,
    currency_type VARCHAR(100) NULL,
    client_code VARCHAR(100) NULL,
    client_name VARCHAR(200) NULL,
    bank_summary VARCHAR(1000) NULL,
    comment VARCHAR(500) NULL,
    client_accounts_bank_no VARCHAR(100) NULL,
    INDEX idx_non_confirm_sum_ebank_number (ebank_number(100)),
    INDEX idx_non_confirm_sum_serial_number (ebank_serial_number(100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS eg_non_confirm_collection_account_checking (
    id BIGINT NOT NULL PRIMARY KEY,
    create_by VARCHAR(64) NULL,
    create_time DATETIME NULL,
    update_by VARCHAR(64) NULL,
    update_time DATETIME NULL,
    del_flag CHAR(1) NULL DEFAULT '0',
    account_checking_month VARCHAR(10) NULL,
    collection_accounts_bank VARCHAR(200) NULL,
    system_code VARCHAR(50) NULL,
    business_ebank_number TEXT NULL,
    ebank_serial_number TEXT NULL,
    business_happen_date DATETIME NULL,
    account_age_class VARCHAR(50) NULL,
    account_age DECIMAL(20,2) NULL,
    month_init_balance DECIMAL(20,2) NULL,
    cur_month_credit_amount DECIMAL(20,2) NULL,
    cur_month_balance DECIMAL(20,2) NULL,
    system_amount DECIMAL(20,2) NULL,
    diff_amount DECIMAL(20,2) NULL,
    account_checking_comments VARCHAR(1000) NULL,
    financial_primary_classic VARCHAR(200) NULL,
    confirm_account_property VARCHAR(200) NULL,
    is_confirmed VARCHAR(10) NULL,
    collection_accounts_bank_code VARCHAR(1000) NULL,
    remark VARCHAR(1000) NULL,
    non_lease_account_checking_comments VARCHAR(1000) NULL,
    non_lease_non_claim_amount DECIMAL(20,2) NULL,
    non_lease_non_claim_reasons VARCHAR(1000) NULL,
    reclass_amount DECIMAL(20,2) NULL,
    reclass_account_number VARCHAR(50) NULL,
    operate_history_comments VARCHAR(2000) NULL,
    INDEX idx_account_checking_month (account_checking_month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS eg_hy_full_online_bank_batch_no_mapping (
    id BIGINT NOT NULL PRIMARY KEY,
    online_bank_no VARCHAR(100) NULL,
    deduct_batch_no VARCHAR(100) NULL,
    create_by VARCHAR(64) NULL,
    create_time DATETIME NULL,
    update_by VARCHAR(64) NULL,
    update_time DATETIME NULL,
    del_flag CHAR(1) NULL DEFAULT '0',
    deduct_category VARCHAR(10) NULL,
    business_line VARCHAR(20) NULL,
    bank_receipt_no VARCHAR(100) NULL,
    collect_amount_time DATETIME NULL,
    collect_amount DECIMAL(20,2) NULL,
    collect_bank VARCHAR(100) NULL,
    collect_bank_account VARCHAR(100) NULL,
    comments VARCHAR(2000) NULL,
    pay_bank_account_name VARCHAR(100) NULL,
    pay_bank VARCHAR(100) NULL,
    pay_bank_account VARCHAR(100) NULL,
    can_charge_off_amount DECIMAL(20,2) NULL,
    already_charge_off_amount DECIMAL(20,2) NULL,
    dec_dongjje DECIMAL(20,2) NULL,
    refund_amount DECIMAL(20,2) NULL,
    collect_amount_account_name VARCHAR(100) NULL,
    refund_flag VARCHAR(10) NULL,
    online_bank_belong VARCHAR(20) NULL,
    sum_id BIGINT NULL,
    client_code VARCHAR(100) NULL,
    client_name VARCHAR(200) NULL,
    INDEX idx_hy_online_bank_no (online_bank_no),
    INDEX idx_hy_deduct_batch_no (deduct_batch_no),
    INDEX idx_hy_sum_id (sum_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
