CREATE TABLE IF NOT EXISTS eg_vehicle_business_model (
  id BIGINT NOT NULL COMMENT 'ID',
  contract_code VARCHAR(100) NOT NULL COMMENT '合同编号',
  source_system VARCHAR(50) COMMENT '来源系统',
  source_event_id VARCHAR(100) COMMENT '来源业务流水号',
  event_code VARCHAR(50) COMMENT '事件编码',
  org_id VARCHAR(100) COMMENT '签约主体',
  business_line VARCHAR(50) COMMENT '业务板块',
  lease_type VARCHAR(50) COMMENT '租赁类型',
  lease_method VARCHAR(50) COMMENT '租赁方式',
  product_code VARCHAR(100) COMMENT '产品编码',
  product_name VARCHAR(200) COMMENT '产品名称',
  guarantee_flag VARCHAR(20) COMMENT '有担无担',
  channel_mode VARCHAR(50) COMMENT '渠道模式',
  dealer_code VARCHAR(100) COMMENT '渠道编码',
  dealer_name VARCHAR(200) COMMENT '渠道名称',
  customer_code VARCHAR(100) COMMENT '客户编号',
  customer_name VARCHAR(200) COMMENT '客户名称',
  contract_sign_date DATE COMMENT '合同签订日',
  lease_start_date DATE COMMENT '起租日',
  maturity_date DATE COMMENT '到期日',
  currency VARCHAR(10) COMMENT '币种',
  contract_amount DECIMAL(20,2) DEFAULT 0 COMMENT '合同总额',
  finance_amount DECIMAL(20,2) DEFAULT 0 COMMENT '融资金额',
  actual_disbursement DECIMAL(20,2) DEFAULT 0 COMMENT '实际投放金额',
  total_terms INT COMMENT '总期数',
  contract_rate DECIMAL(20,6) COMMENT '合同年利率',
  xirr_rate DECIMAL(20,6) COMMENT '实际收益率XIRR',
  residual_value DECIMAL(20,2) DEFAULT 0 COMMENT '留购价',
  repayment_frequency VARCHAR(30) COMMENT '还款频率',
  repayment_method VARCHAR(50) COMMENT '还款方式',
  vin VARCHAR(50) COMMENT '车架号VIN',
  asset_no VARCHAR(100) COMMENT '租赁物编号',
  asset_name VARCHAR(200) COMMENT '车辆名称',
  brand VARCHAR(100) COMMENT '品牌',
  model VARCHAR(100) COMMENT '车型',
  car_type VARCHAR(30) COMMENT '新车二手车',
  original_asset_value DECIMAL(20,2) DEFAULT 0 COMMENT '车辆原值',
  recognized_asset_value DECIMAL(20,2) DEFAULT 0 COMMENT '起租认定价值',
  mortgage_flag VARCHAR(10) COMMENT '是否抵押',
  mortgage_certificate_no VARCHAR(100) COMMENT '抵押权证编号',
  contract_status VARCHAR(50) COMMENT '合同状态',
  five_class VARCHAR(30) COMMENT '五级分类',
  impairment_stage VARCHAR(20) DEFAULT '第一阶段' COMMENT '减值阶段',
  overdue_days INT DEFAULT 0 COMMENT '逾期天数',
  special_status VARCHAR(50) COMMENT '特殊状态',
  create_time DATETIME COMMENT '创建时间',
  update_time DATETIME COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_vehicle_business_contract (contract_code),
  KEY idx_vehicle_business_vin (vin),
  KEY idx_vehicle_business_customer (customer_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='乘用车合同业财模型';
