ALTER TABLE financialdb.eg_contract ADD report_flag varchar(2) NULL;
COMMENT ON COLUMN financialdb.eg_contract.report_flag IS '租赁大表报表查询时是否过滤标志 0:过滤, 1:不过滤';

ALTER TABLE financialdb.eg_account ADD check_flag bpchar(1) NULL;
COMMENT ON COLUMN financialdb.eg_account.check_flag IS '科目是否参与金蝶中间表和金蝶表对账 0:不参与 1:参与';


CREATE TABLE financialdb.eg_recycling_equipment_in (
   id int8 NOT NULL,
   inbound_date varchar(100) NULL,
   org_id varchar(100) NOT NULL,
   financial_exposure numeric(20, 2) NULL,
   recycling_equipment_cost numeric(20, 2) NULL,
   provision_for_impairment numeric(20, 2) NULL,
   process_status varchar(50) NULL,
   is_generate_voucher bpchar(1) NULL DEFAULT '0'::bpchar,
   del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
   create_by varchar(32) NULL,
   create_time timestamp(6) NULL,
   update_by varchar(32) NULL,
   update_time timestamp(6) NULL,
   process_instance_id int8 NULL,
   CONSTRAINT eg_recycling_equipment_pk PRIMARY KEY (id)
);
CREATE INDEX eg_recycling_equipment_in_id_idx ON financialdb.eg_recycling_equipment_in USING btree (id);



CREATE TABLE financialdb.eg_recycling_equipment_in_detail (
  id int8 NOT NULL,
  inbound_date varchar(100) NULL,
  org_id varchar(100) NOT NULL,
  contract_code varchar(100) NOT NULL,
  financial_contract_status varchar(50) NULL,
  client_name varchar(200) NULL,
  receivable_rent_balance numeric(20, 2) NULL,
  receivable_residual_value_balance numeric(20, 2) NULL,
  receivable_outtax_balance numeric(20, 2) NULL,
  unrealized_revenue_balance numeric(20, 2) NULL,
  lessee_margin_balance numeric(20, 2) NULL,
  financial_exposure numeric(20, 2) NULL,
  recycling_equipment_cost numeric(20, 2) NULL,
  provision_for_impairment numeric(20, 2) NULL,
  voucher_id text NULL,
  del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
  create_by varchar(32) NULL,
  create_time timestamp(6) NULL,
  update_by varchar(32) NULL,
  update_time timestamp(6) NULL,
  client_code varchar(100) NULL,
  CONSTRAINT eg_recycling_equipment_in_detail_pk PRIMARY KEY (id)
);
CREATE INDEX eg_recycling_equipment_in_detail_id_idx ON financialdb.eg_recycling_equipment_in_detail USING btree (id);



CREATE TABLE financialdb.eg_recycling_equipment_out_detail (
   id int8 NOT NULL,
   outbound_date varchar(100) NULL,
   org_id varchar(100) NOT NULL,
   contract_code varchar(100) NOT NULL,
   client_name varchar(200) NULL,
   recycling_equipment_cost numeric(20, 2) NULL,
   provision_for_impairment numeric(20, 2) NULL,
   process_status varchar(50) NULL,
   voucher_id text NULL,
   del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
   create_by varchar(32) NULL,
   create_time timestamp(6) NULL,
   update_by varchar(32) NULL,
   update_time timestamp(6) NULL,
   process_instance_id int8 NULL,
   is_generate_voucher bpchar(1) NULL DEFAULT '0'::bpchar,
   client_code varchar(100) NULL,
   CONSTRAINT eg_recycling_equipment_out_detail_pk PRIMARY KEY (id)
);
CREATE INDEX eg_recycling_equipment_out_detail_id_idx ON financialdb.eg_recycling_equipment_out_detail USING btree (id);




CREATE TABLE financialdb.eg_check_account_detail_contract_balance (
    id int8 NOT NULL,
    voucher_id int8 NULL,
    interface_data_id int8 NULL DEFAULT 0,
    system_code varchar(20) NULL,
    business_code varchar(100) NULL,
    business_date timestamp NULL,
    voucher_date timestamp NULL,
    scene_code varchar(100) NULL,
    contract_code varchar(100) NULL,
    client_code varchar(100) NULL,
    client_type varchar(100) NULL,
    org_id varchar(100) NULL,
    create_by varchar(32) NULL,
    create_time timestamp NULL,
    update_by varchar(32) NULL,
    update_time timestamp NULL,
    del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
    receivable_rent_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_rent_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_downpayment_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_downpayment_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_residual_value_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_residual_value_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_commission_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_commission_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_rebate_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_rebate_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_insurance_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_insurance_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_otherincome_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_otherincome_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_outtax_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_outtax_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_outputtax_base_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_outputtax_base_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_unconfirm_receipt_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_unconfirm_receipt_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_service_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_service_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_service_outtax_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_service_outtax_amount numeric(20, 2) NULL DEFAULT 0,
    unrealized_revenue_balance numeric(20, 2) NULL DEFAULT 0,
    unrealized_revenue_amount numeric(20, 2) NULL DEFAULT 0,
    lease_revenue_balance numeric(20, 2) NULL DEFAULT 0,
    lease_revenue_amount numeric(20, 2) NULL DEFAULT 0,
    service_revenue_balance numeric(20, 2) NULL DEFAULT 0,
    service_revenue_amount numeric(20, 2) NULL DEFAULT 0,
    insurance_differ_balance numeric(20, 2) NULL DEFAULT 0,
    insurance_differ_amount numeric(20, 2) NULL DEFAULT 0,
    dinterest_revenue_balance numeric(20, 2) NULL DEFAULT 0,
    dinterest_revenue_amount numeric(20, 2) NULL DEFAULT 0,
    terminate_balance numeric(20, 2) NULL DEFAULT 0,
    terminate_amount numeric(20, 2) NULL DEFAULT 0,
    other_revenue_balance numeric(20, 2) NULL DEFAULT 0,
    other_revenue_amount numeric(20, 2) NULL DEFAULT 0,
    damages_revenue_balance numeric(20, 2) NULL DEFAULT 0,
    damages_revenue_amount numeric(20, 2) NULL DEFAULT 0,
    margin_interest_balance numeric(20, 2) NULL DEFAULT 0,
    margin_interest_amount numeric(20, 2) NULL DEFAULT 0,
    payable_device_estimate_balance numeric(20, 2) NULL DEFAULT 0,
    payable_device_estimate_amount numeric(20, 2) NULL DEFAULT 0,
    payable_device_balance numeric(20, 2) NULL DEFAULT 0,
    payable_device_amount numeric(20, 2) NULL DEFAULT 0,
    payable_other_cost_estimate_balance numeric(20, 2) NULL DEFAULT 0,
    payable_other_cost_estimate_amount numeric(20, 2) NULL DEFAULT 0,
    payable_other_cost_balance numeric(20, 2) NULL DEFAULT 0,
    payable_other_cost_amount numeric(20, 2) NULL DEFAULT 0,
    payable_agency_estimate_balance numeric(20, 2) NULL DEFAULT 0,
    payable_agency_estimate_amount numeric(20, 2) NULL DEFAULT 0,
    payable_agency_balance numeric(20, 2) NULL DEFAULT 0,
    payable_agency_amount numeric(20, 2) NULL DEFAULT 0,
    payable_vehicle_estimate_balance numeric(20, 2) NULL DEFAULT 0,
    payable_vehicle_estimate_amount numeric(20, 2) NULL DEFAULT 0,
    payable_vehicle_balance numeric(20, 2) NULL DEFAULT 0,
    payable_vehicle_amount numeric(20, 2) NULL DEFAULT 0,
    payable_band_cost_estimate_balance numeric(20, 2) NULL DEFAULT 0,
    payable_band_cost_estimate_amount numeric(20, 2) NULL DEFAULT 0,
    payable_band_cost_balance numeric(20, 2) NULL DEFAULT 0,
    payable_band_cost_amount numeric(20, 2) NULL DEFAULT 0,
    payable_pledge_estimate_balance numeric(20, 2) NULL DEFAULT 0,
    payable_pledge_estimate_amount numeric(20, 2) NULL DEFAULT 0,
    payable_pledge_balance numeric(20, 2) NULL DEFAULT 0,
    payable_pledge_amount numeric(20, 2) NULL DEFAULT 0,
    payable_unpledge_estimate_balance numeric(20, 2) NULL DEFAULT 0,
    payable_unpledge_estimate_amount numeric(20, 2) NULL DEFAULT 0,
    payable_unpledge_balance numeric(20, 2) NULL DEFAULT 0,
    payable_unpledge_amount numeric(20, 2) NULL DEFAULT 0,
    lessee_margin_balance numeric(20, 2) NULL DEFAULT 0,
    lessee_margin_amount numeric(20, 2) NULL DEFAULT 0,
    supplier_margin_balance numeric(20, 2) NULL DEFAULT 0,
    supplier_margin_amount numeric(20, 2) NULL DEFAULT 0,
    payable_insurance_estimate_balance numeric(20, 2) NULL DEFAULT 0,
    payable_insurance_estimate_amount numeric(20, 2) NULL DEFAULT 0,
    payable_insurance_balance numeric(20, 2) NULL DEFAULT 0,
    payable_insurance_amount numeric(20, 2) NULL DEFAULT 0,
    intax_balance numeric(20, 2) NULL DEFAULT 0,
    intax_amount numeric(20, 2) NULL DEFAULT 0,
    outtax_balance numeric(20, 2) NULL DEFAULT 0,
    outtax_amount numeric(20, 2) NULL DEFAULT 0,
    litigation_expenses_balance numeric(20, 2) NULL DEFAULT 0,
    litigation_expenses_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_amount numeric(20, 2) NULL DEFAULT 0,
    receive_cost_balance numeric(20, 2) NULL DEFAULT 0,
    receive_cost_amount numeric(20, 2) NULL DEFAULT 0,
    off_income_balance numeric(20, 2) NULL DEFAULT 0,
    off_income_amount numeric(20, 2) NULL DEFAULT 0,
    defer_income_balance numeric(20, 2) NULL DEFAULT 0,
    defer_income_amount numeric(20, 2) NULL DEFAULT 0,
    payable_account_balance numeric(20, 2) NULL DEFAULT 0,
    payable_account_amount numeric(20, 2) NULL DEFAULT 0,
    payable_margin_balance numeric(20, 2) NULL DEFAULT 0,
    payable_margin_amount numeric(20, 2) NULL DEFAULT 0,
    payable_margin_year_balance numeric(20, 2) NULL DEFAULT 0,
    payable_margin_year_amount numeric(20, 2) NULL DEFAULT 0,
    margin_ointerest_balance numeric(20, 2) NULL DEFAULT 0,
    margin_ointerest_amount numeric(20, 2) NULL DEFAULT 0,
    receive_sum_balance numeric(20, 2) NULL DEFAULT 0,
    receive_sum_amount numeric(20, 2) NULL DEFAULT 0,
    receive_sum_outtax_balance numeric(20, 2) NULL DEFAULT 0,
    receive_sum_outtax_amount numeric(20, 2) NULL DEFAULT 0,
    receive_unrealized_revenue_balance numeric(20, 2) NULL DEFAULT 0,
    receive_unrealized_revenue_amount numeric(20, 2) NULL DEFAULT 0,
    payable_lessee_margin_year_balance numeric(20, 2) NULL DEFAULT 0,
    payable_lessee_margin_year_amount numeric(20, 2) NULL DEFAULT 0,
    payable_supplier_margin_year_balance numeric(20, 2) NULL DEFAULT 0,
    payable_supplier_margin_year_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_litigation_expenses_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_litigation_expenses_amount numeric(20, 2) NULL DEFAULT 0,
    payable_other_estimate_balance numeric(20, 2) NULL DEFAULT 0,
    payable_other_estimate_amount numeric(20, 2) NULL DEFAULT 0,
    payable_discount_cost_balance numeric(20, 2) NULL DEFAULT 0,
    payable_discount_cost_amount numeric(20, 2) NULL DEFAULT 0,
    payable_procedure_cost_balance numeric(20, 2) NULL DEFAULT 0,
    payable_procedure_cost_amount numeric(20, 2) NULL DEFAULT 0,
    provisional_receipts_balance numeric(20, 2) NULL DEFAULT 0,
    provisional_receipts_amount numeric(20, 2) NULL DEFAULT 0,
    equipment_depreciation_reserves_balance numeric(20, 2) NULL DEFAULT 0,
    equipment_depreciation_reserves_amount numeric(20, 2) NULL DEFAULT 0,
    equipment_depreciation_loss_balance numeric(20, 2) NULL DEFAULT 0,
    equipment_depreciation_loss_amount numeric(20, 2) NULL DEFAULT 0,
    asset_dispose_gain_balance numeric(20, 2) NULL DEFAULT 0,
    asset_dispose_gain_amount numeric(20, 2) NULL DEFAULT 0,
    asset_dispose_loss_balance numeric(20, 2) NULL DEFAULT 0,
    asset_dispose_loss_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_other_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_other_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_collection_transfer_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_collection_transfer_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_related_party_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_related_party_amount numeric(20, 2) NULL DEFAULT 0,
    collection_transfer_balance numeric(20, 2) NULL DEFAULT 0,
    collection_transfer_amount numeric(20, 2) NULL DEFAULT 0,
    collect_payment_other_balance numeric(20, 2) NULL DEFAULT 0,
    collect_payment_other_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_interest_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_interest_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_litigation_margin_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_litigation_margin_amount numeric(20, 2) NULL DEFAULT 0,
    property_cost_balance numeric(20, 2) NULL DEFAULT 0,
    property_cost_amount numeric(20, 2) NULL DEFAULT 0,
    property_depreciation_reserves_balance numeric(20, 2) NULL DEFAULT 0,
    property_depreciation_reserves_amount numeric(20, 2) NULL DEFAULT 0,
    machine_cost_balance numeric(20, 2) NULL DEFAULT 0,
    machine_cost_amount numeric(20, 2) NULL DEFAULT 0,
    machine_depreciation_reserves_balance numeric(20, 2) NULL DEFAULT 0,
    machine_depreciation_reserves_amount numeric(20, 2) NULL DEFAULT 0,
    other_cost_balance numeric(20, 2) NULL DEFAULT 0,
    other_cost_amount numeric(20, 2) NULL DEFAULT 0,
    other_depreciation_reserves_balance numeric(20, 2) NULL DEFAULT 0,
    other_depreciation_reserves_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_factoring_principal_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_factoring_principal_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_factoring_interest_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_factoring_interest_amount numeric(20, 2) NULL DEFAULT 0,
    payable_discount_cost_outtax_balance numeric(20, 2) NULL DEFAULT 0,
    payable_discount_cost_outtax_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_rent_investment_property_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_rent_investment_property_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_outtax_investment_property_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_outtax_investment_property_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_trade_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_trade_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_service_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_service_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_other_receivable_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_other_receivable_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_temp_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_temp_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_other_margin_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_other_margin_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_investment_property_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_investment_property_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_deposit_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_deposit_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_litigation_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_litigation_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_litigation_margin_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_litigation_margin_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_other_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_other_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_individual_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_individual_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_bill_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_bill_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_gov_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_gov_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_other_long_receibles_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_other_long_receibles_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_long_related_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_long_related_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_interest_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_interest_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_principal_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_principal_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_interest_adjustment_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_interest_adjustment_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_principal_nonfinancial_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_principal_nonfinancial_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_commission_nonfinancial_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_commission_nonfinancial_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_interest_adjustment_nonfinancial_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_interest_adjustment_nonfinancial_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_bank_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_bank_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_buying_back_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_buying_back_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_term_deposit_interest_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_term_deposit_interest_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_borrowings_interest_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_borrowings_interest_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_buying_back_interest_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_buying_back_interest_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_financial_product_interest_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_financial_product_interest_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_structured_deposit_interest_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_structured_deposit_interest_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_fvpl_interest_other_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_fvpl_interest_other_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_bond_fvoci_interest_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_bond_fvoci_interest_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_fvoci_interest_other_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_fvoci_interest_other_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_bond_ac_interest_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_bond_ac_interest_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_ac_interest_other_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_ac_interest_other_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_bond_ac_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_bond_ac_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_turst_ac_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_turst_ac_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_other_financial_ac_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_other_financial_ac_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_other_asset_ac_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_other_asset_ac_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_bond_fvoci_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_bond_fvoci_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_other_financial_fvoci_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_other_financial_fvoci_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_subsidiary_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_subsidiary_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_jv_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_jv_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_associate_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_reserves_associate_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_virtual_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_virtual_amount numeric(20, 2) NULL DEFAULT 0,
    unrealized_revenue_other_balance numeric(20, 2) NULL DEFAULT 0,
    unrealized_revenue_other_amount numeric(20, 2) NULL DEFAULT 0,
    payable_factoring_balance numeric(20, 2) NULL DEFAULT 0,
    payable_factoring_amount numeric(20, 2) NULL DEFAULT 0,
    payable_entrust_balance numeric(20, 2) NULL DEFAULT 0,
    payable_entrust_amount numeric(20, 2) NULL DEFAULT 0,
    collect_claims_balance numeric(20, 2) NULL DEFAULT 0,
    collect_claims_amount numeric(20, 2) NULL DEFAULT 0,
    payable_other_balance numeric(20, 2) NULL DEFAULT 0,
    payable_other_amount numeric(20, 2) NULL DEFAULT 0,
    prereceived_rent_balance numeric(20, 2) NULL DEFAULT 0,
    prereceived_rent_amount numeric(20, 2) NULL DEFAULT 0,
    payable_related_party_balance numeric(20, 2) NULL DEFAULT 0,
    payable_related_party_amount numeric(20, 2) NULL DEFAULT 0,
    other_payable_spv_balance numeric(20, 2) NULL DEFAULT 0,
    other_payable_spv_amount numeric(20, 2) NULL DEFAULT 0,
    other_payable_trust_balance numeric(20, 2) NULL DEFAULT 0,
    other_payable_trust_amount numeric(20, 2) NULL DEFAULT 0,
    other_payable_claim_asset_balance numeric(20, 2) NULL DEFAULT 0,
    other_payable_claim_asset_amount numeric(20, 2) NULL DEFAULT 0,
    other_payable_rent_balance numeric(20, 2) NULL DEFAULT 0,
    other_payable_rent_amount numeric(20, 2) NULL DEFAULT 0,
    other_payable_residual_balance numeric(20, 2) NULL DEFAULT 0,
    other_payable_residual_amount numeric(20, 2) NULL DEFAULT 0,
    other_payable_other_balance numeric(20, 2) NULL DEFAULT 0,
    other_payable_other_amount numeric(20, 2) NULL DEFAULT 0,
    other_payable_claim_balance numeric(20, 2) NULL DEFAULT 0,
    other_payable_claim_amount numeric(20, 2) NULL DEFAULT 0,
    other_payable_claim_other_balance numeric(20, 2) NULL DEFAULT 0,
    other_payable_claim_other_amount numeric(20, 2) NULL DEFAULT 0,
    other_payable_collect_balance numeric(20, 2) NULL DEFAULT 0,
    other_payable_collect_amount numeric(20, 2) NULL DEFAULT 0,
    supplier_pool_balance numeric(20, 2) NULL DEFAULT 0,
    supplier_pool_amount numeric(20, 2) NULL DEFAULT 0,
    agent_margin_balance numeric(20, 2) NULL DEFAULT 0,
    agent_margin_amount numeric(20, 2) NULL DEFAULT 0,
    other_margin_balance numeric(20, 2) NULL DEFAULT 0,
    other_margin_amount numeric(20, 2) NULL DEFAULT 0,
    rent_margin_balance numeric(20, 2) NULL DEFAULT 0,
    rent_margin_amount numeric(20, 2) NULL DEFAULT 0,
    other_long_margin_balance numeric(20, 2) NULL DEFAULT 0,
    other_long_margin_amount numeric(20, 2) NULL DEFAULT 0,
    other_business_income_balance numeric(20, 2) NULL DEFAULT 0,
    other_business_income_amount numeric(20, 2) NULL DEFAULT 0,
    other_income_service_balance numeric(20, 2) NULL DEFAULT 0,
    other_income_service_amount numeric(20, 2) NULL DEFAULT 0,
    interest_other_long_payables_balance numeric(20, 2) NULL DEFAULT 0,
    interest_other_long_payables_amount numeric(20, 2) NULL DEFAULT 0,
    interest_other_financial_ac_balance numeric(20, 2) NULL DEFAULT 0,
    interest_other_financial_ac_amount numeric(20, 2) NULL DEFAULT 0,
    lease_revenue6_balance numeric(20, 2) NULL DEFAULT 0,
    lease_revenue6_amount numeric(20, 2) NULL DEFAULT 0,
    lease_revenue3_balance numeric(20, 2) NULL DEFAULT 0,
    lease_revenue3_amount numeric(20, 2) NULL DEFAULT 0,
    other_income_lease_transfer_balance numeric(20, 2) NULL DEFAULT 0,
    other_income_lease_transfer_amount numeric(20, 2) NULL DEFAULT 0,
    rent_investment_property_balance numeric(20, 2) NULL DEFAULT 0,
    rent_investment_property_amount numeric(20, 2) NULL DEFAULT 0,
    other_income_factoring_transfer_balance numeric(20, 2) NULL DEFAULT 0,
    other_income_factoring_transfer_amount numeric(20, 2) NULL DEFAULT 0,
    asset_dispose_gain_foreclosed_balance numeric(20, 2) NULL DEFAULT 0,
    asset_dispose_gain_foreclosed_amount numeric(20, 2) NULL DEFAULT 0,
    asset_dispose_loss_foreclosed_balance numeric(20, 2) NULL DEFAULT 0,
    asset_dispose_loss_foreclosed_amount numeric(20, 2) NULL DEFAULT 0,
    other_cost_lease_transfer_balance numeric(20, 2) NULL DEFAULT 0,
    other_cost_lease_transfer_amount numeric(20, 2) NULL DEFAULT 0,
    other_cost_factoring_transfer_balance numeric(20, 2) NULL DEFAULT 0,
    other_cost_factoring_transfer_amount numeric(20, 2) NULL DEFAULT 0,
    assessment_fee_balance numeric(20, 2) NULL DEFAULT 0,
    assessment_fee_amount numeric(20, 2) NULL DEFAULT 0,
    attorney_fee_balance numeric(20, 2) NULL DEFAULT 0,
    attorney_fee_amount numeric(20, 2) NULL DEFAULT 0,
    intermediary_fee_other_balance numeric(20, 2) NULL DEFAULT 0,
    intermediary_fee_other_amount numeric(20, 2) NULL DEFAULT 0,
    consultation_fee_balance numeric(20, 2) NULL DEFAULT 0,
    consultation_fee_amount numeric(20, 2) NULL DEFAULT 0,
    notary_fee_balance numeric(20, 2) NULL DEFAULT 0,
    notary_fee_amount numeric(20, 2) NULL DEFAULT 0,
    lease_asset_recovery_fee_balance numeric(20, 2) NULL DEFAULT 0,
    lease_asset_recovery_fee_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_trade_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_trade_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_service_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_service_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_other_receivables_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_other_receivables_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_temp_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_temp_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_other_margin_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_other_margin_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_rent_investment_property_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_rent_investment_property_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_deposit_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_deposit_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_litigation_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_litigation_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_litigation_margin_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_litigation_margin_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_other_receivable_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_other_receivable_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_reverse_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_reverse_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_equity_investment_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_equity_investment_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_interest_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_interest_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_bill_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_bill_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_collateral_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_collateral_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_financial_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_financial_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_buying_back_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_buying_back_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_bond_ac_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_bond_ac_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_financial_fvoci_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_financial_fvoci_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_bank_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_bank_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_trust_ac_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_trust_ac_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_other_asset_ac_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_other_asset_ac_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_other_financial_ac_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_other_financial_ac_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_gov_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_gov_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_other_long_receivables_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_other_long_receivables_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_other_long_related_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_other_long_related_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_borrowings_interest_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_borrowings_interest_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_investment_property_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_investment_property_amount numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_other_balance numeric(20, 2) NULL DEFAULT 0,
    depreciation_loss_other_amount numeric(20, 2) NULL DEFAULT 0,
    publication_fee_balance numeric(20, 2) NULL DEFAULT 0,
    publication_fee_amount numeric(20, 2) NULL DEFAULT 0,
    receive_sum_debt_restructure_balance numeric(20, 2) NULL DEFAULT 0,
    receive_sum_debt_restructure_amount numeric(20, 2) NULL DEFAULT 0,
    unrealized_revenue_debt_restructure_balance numeric(20, 2) NULL DEFAULT 0,
    unrealized_revenue_debt_restructure_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_outtax_debt_restructure_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_outtax_debt_restructure_amount numeric(20, 2) NULL DEFAULT 0,
    unrealized_revenue_other_debt_restructure_balance numeric(20, 2) NULL DEFAULT 0,
    unrealized_revenue_other_debt_restructure_amount numeric(20, 2) NULL DEFAULT 0,
    collect_payment_balance numeric(20, 2) NULL DEFAULT 0,
    collect_payment_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_default_interest_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_default_interest_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_terminate_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_terminate_amount numeric(20, 2) NULL DEFAULT 0,
    litigation_virtual_balance numeric(20, 2) NULL DEFAULT 0,
    litigation_virtual_amount numeric(20, 2) NULL DEFAULT 0,
    period_code int4 NOT NULL,
    eas_voucher_id varchar(50) NULL,
    bill_contract_code varchar(60) NULL,
    receivable_other_revenue_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_other_revenue_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_damages_revenue_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_damages_revenue_amount numeric(20, 2) NULL DEFAULT 0,
    continue_involving_assets_balance numeric(20, 2) NULL DEFAULT 0,
    continue_involving_assets_amount numeric(20, 2) NULL DEFAULT 0,
    payable_margin_entrusted_loans_balance numeric(20, 2) NULL DEFAULT 0,
    payable_margin_entrusted_loans_amount numeric(20, 2) NULL DEFAULT 0,
    continue_involving_debts_balance numeric(20, 2) NULL DEFAULT 0,
    continue_involving_debts_amount numeric(20, 2) NULL DEFAULT 0,
    debt_restructuring_income_balance numeric(20, 2) NULL DEFAULT 0,
    debt_restructuring_income_amount numeric(20, 2) NULL DEFAULT 0,
    lease_transfer_income_balance numeric(20, 2) NULL DEFAULT 0,
    lease_transfer_income_amount numeric(20, 2) NULL DEFAULT 0,
    other_business_cost_balance numeric(20, 2) NULL DEFAULT 0,
    other_business_cost_amount numeric(20, 2) NULL DEFAULT 0,
    financial_institution_fee_balance numeric(20, 2) NULL DEFAULT 0,
    financial_institution_fee_amount numeric(20, 2) NULL DEFAULT 0,
    payable_bill_balance numeric(20, 2) NULL DEFAULT 0,
    payable_bill_amount numeric(20, 2) NULL DEFAULT 0,
    receivable_bill_balance numeric(20, 2) NULL DEFAULT 0,
    receivable_bill_amount numeric(20, 2) NULL DEFAULT 0,
    bank_deposits_balance numeric(20, 2) NULL DEFAULT 0,
    bank_deposits_amount numeric(20, 2) NULL DEFAULT 0,
    CONSTRAINT eg_check_account_detail_contract_balance_pk PRIMARY KEY (id)
);
CREATE INDEX eg_check_account_detail_contract_balance_client_code_idx ON financialdb.eg_check_account_detail_contract_balance USING btree (client_code);
CREATE INDEX eg_check_account_detail_contract_balance_contract_code_idx ON financialdb.eg_check_account_detail_contract_balance USING btree (contract_code);
CREATE INDEX eg_check_account_detail_contract_balance_org_id_idx ON financialdb.eg_check_account_detail_contract_balance USING btree (org_id);



CREATE TABLE financialdb.eg_check_account_detail_record (
    id int8 NOT NULL,
    period_code int4 NOT NULL,
    submit_by varchar(32) NULL,
    check_type varchar(20) NULL,
    execute_status varchar(50) NULL,
    start_time timestamp(6) NULL,
    end_time timestamp(6) NULL,
    del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
    create_by varchar(32) NULL,
    create_time timestamp(6) NULL,
    update_by varchar(32) NULL,
    update_time timestamp(6) NULL,
    check_target varchar NULL,
    CONSTRAINT eg_check_record_pk PRIMARY KEY (id)
);


CREATE TABLE financialdb.eg_check_account_detail_result (
    id bigserial NOT NULL,
    record_id int8 NOT NULL,
    period_code int4 NOT NULL,
    currency_type varchar(50) NULL,
    org_id varchar(100) NULL,
    account_code varchar(32) NULL,
    contract_code varchar(64) NULL,
    client_code varchar(64) NULL,
    account_remain_balance numeric(20, 2) NULL,
    detail_remain_balance numeric(20, 2) NULL,
    diff_flag bpchar(1) NULL DEFAULT '0'::bpchar,
    diff_balance numeric(20, 2) NULL,
    del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
    create_by varchar(32) NULL,
    create_time timestamp(6) NULL,
    update_by varchar(32) NULL,
    update_time timestamp(6) NULL,
    CONSTRAINT eg_check_result_pk PRIMARY KEY (id)
);


CREATE TABLE financialdb.eg_check_account_detail_result_his (
    id bigserial NOT NULL,
    record_id int8 NOT NULL,
    period_code int4 NOT NULL,
    currency_type varchar(50) NULL,
    org_id varchar(100) NULL,
    account_code varchar(32) NULL,
    contract_code varchar(64) NULL,
    client_code varchar(64) NULL,
    account_remain_balance numeric(20, 2) NULL,
    detail_remain_balance numeric(20, 2) NULL,
    diff_flag bpchar(1) NULL DEFAULT '0'::bpchar,
    diff_balance numeric(20, 2) NULL,
    del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
    create_by varchar(32) NULL,
    create_time timestamp(6) NULL,
    update_by varchar(32) NULL,
    update_time timestamp(6) NULL,
    CONSTRAINT eg_check_result_his_pk PRIMARY KEY (id)
);


CREATE TABLE financialdb.eg_check_account_kingdee_result (
     id bigserial NOT NULL,
     record_id int8 NOT NULL,
     period_code int4 NOT NULL,
     currency_type varchar(50) NULL,
     org_id varchar(100) NULL,
     account_code varchar(32) NULL,
     account_remain_balance numeric(20, 2) NULL,
     kingdee_remain_balance numeric(20, 2) NULL,
     diff_flag bpchar(1) NULL DEFAULT '0'::bpchar,
     diff_balance numeric(20, 2) NULL,
     del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
     create_by varchar(32) NULL,
     create_time timestamp(6) NULL,
     update_by varchar(32) NULL,
     update_time timestamp(6) NULL,
     CONSTRAINT eg_check_account_kingdee_result_pk PRIMARY KEY (id)
);


CREATE TABLE financialdb.eg_check_account_kingdee_result_his (
     id bigserial NOT NULL,
     record_id int8 NOT NULL,
     period_code int4 NOT NULL,
     currency_type varchar(50) NULL,
     org_id varchar(100) NULL,
     account_code varchar(32) NULL,
     account_remain_balance numeric(20, 2) NULL,
     kingdee_remain_balance numeric(20, 2) NULL,
     diff_flag bpchar(1) NULL DEFAULT '0'::bpchar,
     diff_balance numeric(20, 2) NULL,
     del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
     create_by varchar(32) NULL,
     create_time timestamp(6) NULL,
     update_by varchar(32) NULL,
     update_time timestamp(6) NULL,
     CONSTRAINT eg_check_account_kingdee_result_his_pk PRIMARY KEY (id)
);


CREATE TABLE financialdb.eg_check_account_kingdee_tmp (
      id bigserial NOT NULL,
      period_code int4 NOT NULL,
      currency_type varchar(50) NULL,
      org_id varchar(100) NULL,
      account_code varchar(32) NULL,
      fbegin_balance_for numeric(20, 2) NULL,
      fend_balance_for numeric(20, 2) NULL,
      CONSTRAINT eg_check_account_kingdee_tmp_pk PRIMARY KEY (id)
);


CREATE TABLE financialdb.eg_check_account_middle_result (
    id bigserial NOT NULL,
    record_id int8 NOT NULL,
    period_code int4 NOT NULL,
    currency_type varchar(50) NULL,
    org_id varchar(100) NULL,
    account_code varchar(32) NULL,
    client_code varchar(64) NULL,
    contract_code varchar(64) NULL,
    bank_account varchar(400) NULL,
    bill_contract_code varchar(60) NULL,
    account_remain_balance numeric(20, 2) NULL,
    kingdee_remain_balance numeric(20, 2) NULL,
    diff_flag bpchar(1) NULL DEFAULT '0'::bpchar,
    diff_balance numeric(20, 2) NULL,
    del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
    create_by varchar(32) NULL,
    create_time timestamp(6) NULL,
    update_by varchar(32) NULL,
    update_time timestamp(6) NULL,
    CONSTRAINT eg_check_account_middle_result_pk PRIMARY KEY (id)
);


CREATE TABLE financialdb.eg_check_account_middle_result_his (
    id bigserial NOT NULL,
    record_id int8 NOT NULL,
    period_code int4 NOT NULL,
    currency_type varchar(50) NULL,
    org_id varchar(100) NULL,
    account_code varchar(32) NULL,
    client_code varchar(64) NULL,
    contract_code varchar(64) NULL,
    bank_account varchar(400) NULL,
    bill_contract_code varchar(60) NULL,
    account_remain_balance numeric(20, 2) NULL,
    kingdee_remain_balance numeric(20, 2) NULL,
    diff_flag bpchar(1) NULL DEFAULT '0'::bpchar,
    diff_balance numeric(20, 2) NULL,
    del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
    create_by varchar(32) NULL,
    create_time timestamp(6) NULL,
    update_by varchar(32) NULL,
    update_time timestamp(6) NULL,
    CONSTRAINT eg_check_account_middle_result_his_pk PRIMARY KEY (id)
);

CREATE TABLE financialdb.eg_check_account_middle_tmp (
     id bigserial NOT NULL,
     business_date varchar(64) NULL,
     voucher_date varchar(64) NULL,
     system_code varchar(64) NULL,
     period_code int4 NOT NULL,
     currency_type varchar(50) NULL,
     org_id varchar(100) NULL,
     account_code varchar(32) NULL,
     client_code varchar(64) NULL,
     contract_code varchar(64) NULL,
     bank_account varchar(400) NULL,
     bill_contract_code varchar(60) NULL,
     debit_amount numeric(20, 2) NULL,
     credit_amount numeric(20, 2) NULL,
     CONSTRAINT eg_check_account_middle_tmp_pk PRIMARY KEY (id)
);



CREATE OR REPLACE FUNCTION financialdb.auto_insert_eg_check_common_data()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
    -- 分区后缀
column_name text := TG_ARGV[0];
    yyyymmddHHmmss text := to_char(NEW.execute_date,'yyyy-mm-dd hh24:mi:ss');
    yyyymmdd text := to_char(NEW.execute_date,'yyyymmdd');
    yyyymm text := to_char(NEW.execute_date,'yyyymm');
    isExist boolean;
    strSQL  text;
    startTime text;
    endTime text;
begin

	--判断对应分区表是否存在
select count(*) INTO isExist from pg_class where relname = (TG_RELNAME||'_'||yyyymmdd);
--若不存在分区表：
if (isExist = false) then
	   --创建子分区表
	    startTime := yyyymm||'01 00:00:00';
	    endTime := date_trunc('month',NEW.execute_date)  + interval '1 month';
	    strSQL := 'create table if not exists '|| TG_RELNAME ||'_'||yyyymmdd||
	              ' ( CHECK('|| column_name ||'>='''|| startTime ||'''
                    AND '|| column_name ||'< '''|| endTime ||''' )
                    ) INHERITS ('||TG_RELNAME||') ;'  ;
EXECUTE strSQL;
-- 创建索引
strSQL := 'CREATE INDEX '||TG_RELNAME||'_'||yyyymmdd||'_INDEX_'||column_name|| ' ON '
                 ||TG_RELNAME||'_'||yyyymmdd||' ('||column_name||');' ;
EXECUTE strSQL;

end if;
    -- 插入数据到子分区
       strSQL := 'INSERT INTO '||TG_RELNAME||'_'||yyyymmdd||' SELECT $1.* ;' ;
EXECUTE strSQL USING NEW;
RETURN NULL;
END

$function$
;


CREATE TABLE financialdb.eg_check_common_data (
      id int8 NOT NULL,
      execute_date timestamp(6) NOT NULL,
      business_type varchar(100) NULL,
      join_field varchar(4000) NULL,
      query_field varchar(4000) NULL,
      del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
      create_by varchar(32) NULL,
      create_time timestamp(6) NULL,
      update_by varchar(32) NULL,
      update_time timestamp(6) NULL,
      db_code varchar(100) NULL,
      show_field varchar(4000) NULL,
      CONSTRAINT eg_check_common_data_pk PRIMARY KEY (id)
);
CREATE INDEX eg_check_common_data_business_type_idx ON financialdb.eg_check_common_data USING btree (business_type);
CREATE INDEX eg_check_common_data_db_code_idx ON financialdb.eg_check_common_data USING btree (db_code);

-- Table Triggers

create trigger eg_check_common_data_trigger before
    insert
    on
financialdb.eg_check_common_data for each row execute function auto_insert_eg_check_common_data('execute_date');


CREATE TABLE financialdb.eg_check_common_data_result (
     id int8 NOT NULL,
     execute_date timestamp(6) NOT NULL,
     business_type varchar(100) NULL,
     join_field varchar(4000) NULL,
     query_field varchar(4000) NULL,
     del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
     create_by varchar(32) NULL,
     create_time timestamp(6) NULL,
     update_by varchar(32) NULL,
     update_time timestamp(6) NULL,
     db_code varchar(100) NULL,
     show_field varchar(4000) NULL,
     CONSTRAINT eg_check_common_data_result_pk PRIMARY KEY (id)
);
CREATE INDEX eg_check_common_data_result_business_type_idx ON financialdb.eg_check_common_data_result USING btree (business_type);
CREATE INDEX eg_check_common_data_result_db_code_idx ON financialdb.eg_check_common_data_result USING btree (db_code);

-- Table Triggers

create trigger eg_check_common_data_trigger before
    insert
    on
financialdb.eg_check_common_data_result for each row execute function auto_insert_eg_check_common_data('execute_date');


CREATE TABLE financialdb.eg_check_common_field (
       id int8 NOT NULL,
       db_code varchar(100) NULL,
       business_type varchar(100) NULL,
       common_field varchar(200) NULL,
       field_type varchar(10) NULL,
       del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
       create_by varchar(32) NULL,
       create_time timestamp(6) NULL,
       update_by varchar(32) NULL,
       update_time timestamp(6) NULL,
       field_order int4 NULL,
       CONSTRAINT eg_check_common_field_pk PRIMARY KEY (id)
);


CREATE TABLE financialdb.eg_check_common_finance_data (
      id int8 NOT NULL,
      execute_date timestamp(6) NOT NULL,
      business_type varchar(100) NULL,
      join_field varchar(4000) NULL,
      query_field varchar(4000) NULL,
      del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
      create_by varchar(32) NULL,
      create_time timestamp(6) NULL,
      update_by varchar(32) NULL,
      update_time timestamp(6) NULL,
      db_code varchar(100) NULL,
      show_field varchar(4000) NULL,
      CONSTRAINT eg_check_common_finance_data_pk PRIMARY KEY (id)
);
CREATE INDEX eg_check_common_finance_data_business_type_idx ON financialdb.eg_check_common_finance_data USING btree (business_type);
CREATE INDEX eg_check_common_finance_data_db_code_idx ON financialdb.eg_check_common_finance_data USING btree (db_code);

-- Table Triggers

create trigger eg_check_common_data_trigger before
    insert
    on
financialdb.eg_check_common_finance_data for each row execute function auto_insert_eg_check_common_data('execute_date');



CREATE TABLE financialdb.eg_check_common_finance_data_result (
     id int8 NOT NULL,
     record_id int8 NOT NULL,
     execute_date timestamp(6) NOT NULL,
     business_type varchar(100) NULL,
     join_field varchar(4000) NULL,
     query_field varchar(4000) NULL,
     del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
     create_by varchar(32) NULL,
     create_time timestamp(6) NULL,
     update_by varchar(32) NULL,
     update_time timestamp(6) NULL,
     db_code varchar(100) NULL,
     show_field varchar(4000) NULL,
     compare_result_field varchar(4000) NULL,
     compare_flag_field varchar(4000) NULL,
     CONSTRAINT eg_check_common_finance_data_result_pk PRIMARY KEY (id)
);
CREATE INDEX eg_check_common_finance_data_result_business_type_idx ON financialdb.eg_check_common_finance_data_result USING btree (business_type);
CREATE INDEX eg_check_common_finance_data_result_db_code_idx ON financialdb.eg_check_common_finance_data_result USING btree (db_code);

-- Table Triggers

create trigger eg_check_common_data_trigger before
    insert
    on
financialdb.eg_check_common_finance_data_result for each row execute function auto_insert_eg_check_common_data('execute_date');


CREATE TABLE financialdb.eg_check_sql (
      id int8 NOT NULL,
      profile_code varchar(10) NULL,
      db_code varchar(100) NULL,
      query_sql text NULL,
      sql_descr varchar(400) NULL,
      del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
      create_by varchar(32) NULL,
      create_time timestamp(6) NULL,
      update_by varchar(32) NULL,
      update_time timestamp(6) NULL,
      sql_mark varchar(100) NULL,
      finance_query_sql text NULL,
      sql_order int4 NULL,
      CONSTRAINT eg_check_sql_pk PRIMARY KEY (id)
);



CREATE OR REPLACE FUNCTION financialdb.auto_insert_into_tbl_month_partition()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
declare
    -- 分区后缀
column_name text := TG_ARGV[0];
--    yyyymmddHHmmss text := to_char(NEW.execute_date,'yyyy-mm-dd hh24:mi:ss');
--    yyyymmdd text := to_char(NEW.execute_date,'yyyymmdd');
--    yyyymm text := to_char(NEW.execute_date,'yyyymm');
    yyyymm text := NEW.period_code::text;
    isExist boolean;
    strSQL  text;
    startTime text;
    endTime text;
begin
 	RAISE NOTICE 'xxxxx column_name: %',column_name;
	--判断对应分区表是否存在
select count(*) INTO isExist from pg_class where relname = (TG_RELNAME||'_'||yyyymm);
--若不存在分区表：
if (isExist = false) then
	   --创建子分区表
	    startTime := date_trunc('month',to_date(yyyymm, 'YYYYMM'));
	    endTime := date_trunc('month',to_date(CAST(yyyymm AS text), 'YYYYMM')) + interval '1 month';
	    RAISE NOTICE 'xxxxx startTime:%',startTime;
	    RAISE NOTICE 'xxxxx endTime:%',endTime;
	    strSQL := 'create table if not exists '|| TG_RELNAME ||'_'||yyyymm||
	              ' ( CHECK(to_date('|| column_name ||'::text, ''YYYYMM'')>='''|| startTime ||'''
                    AND to_date('|| column_name ||'::text, ''YYYYMM'')< '''|| endTime ||''' )
                    ) INHERITS ('||TG_RELNAME||') ;'  ;
EXECUTE strSQL;
-- 创建索引
strSQL := 'CREATE INDEX '||TG_RELNAME||'_'||yyyymm||'_INDEX_'||column_name|| ' ON '
                 ||TG_RELNAME||'_'||yyyymm||' ('||column_name||');' ;
EXECUTE strSQL;

end if;
    -- 插入数据到子分区
       strSQL := 'INSERT INTO '||TG_RELNAME||'_'||yyyymm||' SELECT $1.* ;' ;
EXECUTE strSQL USING NEW;
RETURN NULL;
END

$function$
;



CREATE TABLE financialdb.eg_contract_balance_month (
       id int8 NOT NULL,
       voucher_id int8 NULL,
       interface_data_id int8 NULL DEFAULT 0,
       system_code varchar(20) NULL,
       business_code varchar(100) NULL,
       business_date timestamp NULL,
       voucher_date timestamp NULL,
       scene_code varchar(100) NULL,
       contract_code varchar(100) NULL,
       client_code varchar(100) NULL,
       client_type varchar(100) NULL,
       org_id varchar(100) NULL,
       create_by varchar(32) NULL,
       create_time timestamp NULL,
       update_by varchar(32) NULL,
       update_time timestamp NULL,
       del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
       receivable_rent_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_rent_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_downpayment_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_downpayment_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_residual_value_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_residual_value_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_commission_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_commission_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_rebate_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_rebate_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_insurance_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_insurance_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_otherincome_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_otherincome_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_outtax_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_outtax_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_outputtax_base_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_outputtax_base_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_unconfirm_receipt_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_unconfirm_receipt_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_service_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_service_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_service_outtax_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_service_outtax_amount numeric(20, 2) NULL DEFAULT 0,
       unrealized_revenue_balance numeric(20, 2) NULL DEFAULT 0,
       unrealized_revenue_amount numeric(20, 2) NULL DEFAULT 0,
       lease_revenue_balance numeric(20, 2) NULL DEFAULT 0,
       lease_revenue_amount numeric(20, 2) NULL DEFAULT 0,
       service_revenue_balance numeric(20, 2) NULL DEFAULT 0,
       service_revenue_amount numeric(20, 2) NULL DEFAULT 0,
       insurance_differ_balance numeric(20, 2) NULL DEFAULT 0,
       insurance_differ_amount numeric(20, 2) NULL DEFAULT 0,
       dinterest_revenue_balance numeric(20, 2) NULL DEFAULT 0,
       dinterest_revenue_amount numeric(20, 2) NULL DEFAULT 0,
       terminate_balance numeric(20, 2) NULL DEFAULT 0,
       terminate_amount numeric(20, 2) NULL DEFAULT 0,
       other_revenue_balance numeric(20, 2) NULL DEFAULT 0,
       other_revenue_amount numeric(20, 2) NULL DEFAULT 0,
       damages_revenue_balance numeric(20, 2) NULL DEFAULT 0,
       damages_revenue_amount numeric(20, 2) NULL DEFAULT 0,
       margin_interest_balance numeric(20, 2) NULL DEFAULT 0,
       margin_interest_amount numeric(20, 2) NULL DEFAULT 0,
       payable_device_estimate_balance numeric(20, 2) NULL DEFAULT 0,
       payable_device_estimate_amount numeric(20, 2) NULL DEFAULT 0,
       payable_device_balance numeric(20, 2) NULL DEFAULT 0,
       payable_device_amount numeric(20, 2) NULL DEFAULT 0,
       payable_other_cost_estimate_balance numeric(20, 2) NULL DEFAULT 0,
       payable_other_cost_estimate_amount numeric(20, 2) NULL DEFAULT 0,
       payable_other_cost_balance numeric(20, 2) NULL DEFAULT 0,
       payable_other_cost_amount numeric(20, 2) NULL DEFAULT 0,
       payable_agency_estimate_balance numeric(20, 2) NULL DEFAULT 0,
       payable_agency_estimate_amount numeric(20, 2) NULL DEFAULT 0,
       payable_agency_balance numeric(20, 2) NULL DEFAULT 0,
       payable_agency_amount numeric(20, 2) NULL DEFAULT 0,
       payable_vehicle_estimate_balance numeric(20, 2) NULL DEFAULT 0,
       payable_vehicle_estimate_amount numeric(20, 2) NULL DEFAULT 0,
       payable_vehicle_balance numeric(20, 2) NULL DEFAULT 0,
       payable_vehicle_amount numeric(20, 2) NULL DEFAULT 0,
       payable_band_cost_estimate_balance numeric(20, 2) NULL DEFAULT 0,
       payable_band_cost_estimate_amount numeric(20, 2) NULL DEFAULT 0,
       payable_band_cost_balance numeric(20, 2) NULL DEFAULT 0,
       payable_band_cost_amount numeric(20, 2) NULL DEFAULT 0,
       payable_pledge_estimate_balance numeric(20, 2) NULL DEFAULT 0,
       payable_pledge_estimate_amount numeric(20, 2) NULL DEFAULT 0,
       payable_pledge_balance numeric(20, 2) NULL DEFAULT 0,
       payable_pledge_amount numeric(20, 2) NULL DEFAULT 0,
       payable_unpledge_estimate_balance numeric(20, 2) NULL DEFAULT 0,
       payable_unpledge_estimate_amount numeric(20, 2) NULL DEFAULT 0,
       payable_unpledge_balance numeric(20, 2) NULL DEFAULT 0,
       payable_unpledge_amount numeric(20, 2) NULL DEFAULT 0,
       lessee_margin_balance numeric(20, 2) NULL DEFAULT 0,
       lessee_margin_amount numeric(20, 2) NULL DEFAULT 0,
       supplier_margin_balance numeric(20, 2) NULL DEFAULT 0,
       supplier_margin_amount numeric(20, 2) NULL DEFAULT 0,
       payable_insurance_estimate_balance numeric(20, 2) NULL DEFAULT 0,
       payable_insurance_estimate_amount numeric(20, 2) NULL DEFAULT 0,
       payable_insurance_balance numeric(20, 2) NULL DEFAULT 0,
       payable_insurance_amount numeric(20, 2) NULL DEFAULT 0,
       intax_balance numeric(20, 2) NULL DEFAULT 0,
       intax_amount numeric(20, 2) NULL DEFAULT 0,
       outtax_balance numeric(20, 2) NULL DEFAULT 0,
       outtax_amount numeric(20, 2) NULL DEFAULT 0,
       litigation_expenses_balance numeric(20, 2) NULL DEFAULT 0,
       litigation_expenses_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_amount numeric(20, 2) NULL DEFAULT 0,
       receive_cost_balance numeric(20, 2) NULL DEFAULT 0,
       receive_cost_amount numeric(20, 2) NULL DEFAULT 0,
       off_income_balance numeric(20, 2) NULL DEFAULT 0,
       off_income_amount numeric(20, 2) NULL DEFAULT 0,
       defer_income_balance numeric(20, 2) NULL DEFAULT 0,
       defer_income_amount numeric(20, 2) NULL DEFAULT 0,
       payable_account_balance numeric(20, 2) NULL DEFAULT 0,
       payable_account_amount numeric(20, 2) NULL DEFAULT 0,
       payable_margin_balance numeric(20, 2) NULL DEFAULT 0,
       payable_margin_amount numeric(20, 2) NULL DEFAULT 0,
       payable_margin_year_balance numeric(20, 2) NULL DEFAULT 0,
       payable_margin_year_amount numeric(20, 2) NULL DEFAULT 0,
       margin_ointerest_balance numeric(20, 2) NULL DEFAULT 0,
       margin_ointerest_amount numeric(20, 2) NULL DEFAULT 0,
       receive_sum_balance numeric(20, 2) NULL DEFAULT 0,
       receive_sum_amount numeric(20, 2) NULL DEFAULT 0,
       receive_sum_outtax_balance numeric(20, 2) NULL DEFAULT 0,
       receive_sum_outtax_amount numeric(20, 2) NULL DEFAULT 0,
       receive_unrealized_revenue_balance numeric(20, 2) NULL DEFAULT 0,
       receive_unrealized_revenue_amount numeric(20, 2) NULL DEFAULT 0,
       payable_lessee_margin_year_balance numeric(20, 2) NULL DEFAULT 0,
       payable_lessee_margin_year_amount numeric(20, 2) NULL DEFAULT 0,
       payable_supplier_margin_year_balance numeric(20, 2) NULL DEFAULT 0,
       payable_supplier_margin_year_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_litigation_expenses_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_litigation_expenses_amount numeric(20, 2) NULL DEFAULT 0,
       payable_other_estimate_balance numeric(20, 2) NULL DEFAULT 0,
       payable_other_estimate_amount numeric(20, 2) NULL DEFAULT 0,
       payable_discount_cost_balance numeric(20, 2) NULL DEFAULT 0,
       payable_discount_cost_amount numeric(20, 2) NULL DEFAULT 0,
       payable_procedure_cost_balance numeric(20, 2) NULL DEFAULT 0,
       payable_procedure_cost_amount numeric(20, 2) NULL DEFAULT 0,
       provisional_receipts_balance numeric(20, 2) NULL DEFAULT 0,
       provisional_receipts_amount numeric(20, 2) NULL DEFAULT 0,
       equipment_depreciation_reserves_balance numeric(20, 2) NULL DEFAULT 0,
       equipment_depreciation_reserves_amount numeric(20, 2) NULL DEFAULT 0,
       equipment_depreciation_loss_balance numeric(20, 2) NULL DEFAULT 0,
       equipment_depreciation_loss_amount numeric(20, 2) NULL DEFAULT 0,
       asset_dispose_gain_balance numeric(20, 2) NULL DEFAULT 0,
       asset_dispose_gain_amount numeric(20, 2) NULL DEFAULT 0,
       asset_dispose_loss_balance numeric(20, 2) NULL DEFAULT 0,
       asset_dispose_loss_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_other_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_other_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_collection_transfer_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_collection_transfer_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_related_party_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_related_party_amount numeric(20, 2) NULL DEFAULT 0,
       collection_transfer_balance numeric(20, 2) NULL DEFAULT 0,
       collection_transfer_amount numeric(20, 2) NULL DEFAULT 0,
       collect_payment_other_balance numeric(20, 2) NULL DEFAULT 0,
       collect_payment_other_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_interest_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_interest_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_litigation_margin_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_litigation_margin_amount numeric(20, 2) NULL DEFAULT 0,
       property_cost_balance numeric(20, 2) NULL DEFAULT 0,
       property_cost_amount numeric(20, 2) NULL DEFAULT 0,
       property_depreciation_reserves_balance numeric(20, 2) NULL DEFAULT 0,
       property_depreciation_reserves_amount numeric(20, 2) NULL DEFAULT 0,
       machine_cost_balance numeric(20, 2) NULL DEFAULT 0,
       machine_cost_amount numeric(20, 2) NULL DEFAULT 0,
       machine_depreciation_reserves_balance numeric(20, 2) NULL DEFAULT 0,
       machine_depreciation_reserves_amount numeric(20, 2) NULL DEFAULT 0,
       other_cost_balance numeric(20, 2) NULL DEFAULT 0,
       other_cost_amount numeric(20, 2) NULL DEFAULT 0,
       other_depreciation_reserves_balance numeric(20, 2) NULL DEFAULT 0,
       other_depreciation_reserves_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_factoring_principal_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_factoring_principal_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_factoring_interest_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_factoring_interest_amount numeric(20, 2) NULL DEFAULT 0,
       payable_discount_cost_outtax_balance numeric(20, 2) NULL DEFAULT 0,
       payable_discount_cost_outtax_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_rent_investment_property_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_rent_investment_property_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_outtax_investment_property_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_outtax_investment_property_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_trade_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_trade_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_service_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_service_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_other_receivable_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_other_receivable_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_temp_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_temp_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_other_margin_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_other_margin_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_investment_property_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_investment_property_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_deposit_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_deposit_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_litigation_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_litigation_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_litigation_margin_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_litigation_margin_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_other_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_other_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_individual_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_individual_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_bill_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_bill_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_gov_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_gov_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_other_long_receibles_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_other_long_receibles_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_long_related_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_long_related_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_interest_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_interest_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_principal_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_principal_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_interest_adjustment_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_interest_adjustment_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_principal_nonfinancial_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_principal_nonfinancial_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_commission_nonfinancial_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_commission_nonfinancial_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_interest_adjustment_nonfinancial_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_interest_adjustment_nonfinancial_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_bank_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_bank_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_buying_back_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_buying_back_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_term_deposit_interest_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_term_deposit_interest_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_borrowings_interest_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_borrowings_interest_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_buying_back_interest_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_buying_back_interest_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_financial_product_interest_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_financial_product_interest_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_structured_deposit_interest_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_structured_deposit_interest_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_fvpl_interest_other_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_fvpl_interest_other_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_bond_fvoci_interest_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_bond_fvoci_interest_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_fvoci_interest_other_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_fvoci_interest_other_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_bond_ac_interest_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_bond_ac_interest_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_ac_interest_other_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_ac_interest_other_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_bond_ac_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_bond_ac_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_turst_ac_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_turst_ac_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_other_financial_ac_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_other_financial_ac_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_other_asset_ac_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_other_asset_ac_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_bond_fvoci_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_bond_fvoci_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_other_financial_fvoci_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_other_financial_fvoci_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_subsidiary_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_subsidiary_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_jv_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_jv_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_associate_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_reserves_associate_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_virtual_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_virtual_amount numeric(20, 2) NULL DEFAULT 0,
       unrealized_revenue_other_balance numeric(20, 2) NULL DEFAULT 0,
       unrealized_revenue_other_amount numeric(20, 2) NULL DEFAULT 0,
       payable_factoring_balance numeric(20, 2) NULL DEFAULT 0,
       payable_factoring_amount numeric(20, 2) NULL DEFAULT 0,
       payable_entrust_balance numeric(20, 2) NULL DEFAULT 0,
       payable_entrust_amount numeric(20, 2) NULL DEFAULT 0,
       collect_claims_balance numeric(20, 2) NULL DEFAULT 0,
       collect_claims_amount numeric(20, 2) NULL DEFAULT 0,
       payable_other_balance numeric(20, 2) NULL DEFAULT 0,
       payable_other_amount numeric(20, 2) NULL DEFAULT 0,
       prereceived_rent_balance numeric(20, 2) NULL DEFAULT 0,
       prereceived_rent_amount numeric(20, 2) NULL DEFAULT 0,
       payable_related_party_balance numeric(20, 2) NULL DEFAULT 0,
       payable_related_party_amount numeric(20, 2) NULL DEFAULT 0,
       other_payable_spv_balance numeric(20, 2) NULL DEFAULT 0,
       other_payable_spv_amount numeric(20, 2) NULL DEFAULT 0,
       other_payable_trust_balance numeric(20, 2) NULL DEFAULT 0,
       other_payable_trust_amount numeric(20, 2) NULL DEFAULT 0,
       other_payable_claim_asset_balance numeric(20, 2) NULL DEFAULT 0,
       other_payable_claim_asset_amount numeric(20, 2) NULL DEFAULT 0,
       other_payable_rent_balance numeric(20, 2) NULL DEFAULT 0,
       other_payable_rent_amount numeric(20, 2) NULL DEFAULT 0,
       other_payable_residual_balance numeric(20, 2) NULL DEFAULT 0,
       other_payable_residual_amount numeric(20, 2) NULL DEFAULT 0,
       other_payable_other_balance numeric(20, 2) NULL DEFAULT 0,
       other_payable_other_amount numeric(20, 2) NULL DEFAULT 0,
       other_payable_claim_balance numeric(20, 2) NULL DEFAULT 0,
       other_payable_claim_amount numeric(20, 2) NULL DEFAULT 0,
       other_payable_claim_other_balance numeric(20, 2) NULL DEFAULT 0,
       other_payable_claim_other_amount numeric(20, 2) NULL DEFAULT 0,
       other_payable_collect_balance numeric(20, 2) NULL DEFAULT 0,
       other_payable_collect_amount numeric(20, 2) NULL DEFAULT 0,
       supplier_pool_balance numeric(20, 2) NULL DEFAULT 0,
       supplier_pool_amount numeric(20, 2) NULL DEFAULT 0,
       agent_margin_balance numeric(20, 2) NULL DEFAULT 0,
       agent_margin_amount numeric(20, 2) NULL DEFAULT 0,
       other_margin_balance numeric(20, 2) NULL DEFAULT 0,
       other_margin_amount numeric(20, 2) NULL DEFAULT 0,
       rent_margin_balance numeric(20, 2) NULL DEFAULT 0,
       rent_margin_amount numeric(20, 2) NULL DEFAULT 0,
       other_long_margin_balance numeric(20, 2) NULL DEFAULT 0,
       other_long_margin_amount numeric(20, 2) NULL DEFAULT 0,
       other_business_income_balance numeric(20, 2) NULL DEFAULT 0,
       other_business_income_amount numeric(20, 2) NULL DEFAULT 0,
       other_income_service_balance numeric(20, 2) NULL DEFAULT 0,
       other_income_service_amount numeric(20, 2) NULL DEFAULT 0,
       interest_other_long_payables_balance numeric(20, 2) NULL DEFAULT 0,
       interest_other_long_payables_amount numeric(20, 2) NULL DEFAULT 0,
       interest_other_financial_ac_balance numeric(20, 2) NULL DEFAULT 0,
       interest_other_financial_ac_amount numeric(20, 2) NULL DEFAULT 0,
       lease_revenue6_balance numeric(20, 2) NULL DEFAULT 0,
       lease_revenue6_amount numeric(20, 2) NULL DEFAULT 0,
       lease_revenue3_balance numeric(20, 2) NULL DEFAULT 0,
       lease_revenue3_amount numeric(20, 2) NULL DEFAULT 0,
       other_income_lease_transfer_balance numeric(20, 2) NULL DEFAULT 0,
       other_income_lease_transfer_amount numeric(20, 2) NULL DEFAULT 0,
       rent_investment_property_balance numeric(20, 2) NULL DEFAULT 0,
       rent_investment_property_amount numeric(20, 2) NULL DEFAULT 0,
       other_income_factoring_transfer_balance numeric(20, 2) NULL DEFAULT 0,
       other_income_factoring_transfer_amount numeric(20, 2) NULL DEFAULT 0,
       asset_dispose_gain_foreclosed_balance numeric(20, 2) NULL DEFAULT 0,
       asset_dispose_gain_foreclosed_amount numeric(20, 2) NULL DEFAULT 0,
       asset_dispose_loss_foreclosed_balance numeric(20, 2) NULL DEFAULT 0,
       asset_dispose_loss_foreclosed_amount numeric(20, 2) NULL DEFAULT 0,
       other_cost_lease_transfer_balance numeric(20, 2) NULL DEFAULT 0,
       other_cost_lease_transfer_amount numeric(20, 2) NULL DEFAULT 0,
       other_cost_factoring_transfer_balance numeric(20, 2) NULL DEFAULT 0,
       other_cost_factoring_transfer_amount numeric(20, 2) NULL DEFAULT 0,
       assessment_fee_balance numeric(20, 2) NULL DEFAULT 0,
       assessment_fee_amount numeric(20, 2) NULL DEFAULT 0,
       attorney_fee_balance numeric(20, 2) NULL DEFAULT 0,
       attorney_fee_amount numeric(20, 2) NULL DEFAULT 0,
       intermediary_fee_other_balance numeric(20, 2) NULL DEFAULT 0,
       intermediary_fee_other_amount numeric(20, 2) NULL DEFAULT 0,
       consultation_fee_balance numeric(20, 2) NULL DEFAULT 0,
       consultation_fee_amount numeric(20, 2) NULL DEFAULT 0,
       notary_fee_balance numeric(20, 2) NULL DEFAULT 0,
       notary_fee_amount numeric(20, 2) NULL DEFAULT 0,
       lease_asset_recovery_fee_balance numeric(20, 2) NULL DEFAULT 0,
       lease_asset_recovery_fee_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_trade_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_trade_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_service_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_service_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_other_receivables_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_other_receivables_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_temp_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_temp_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_other_margin_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_other_margin_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_rent_investment_property_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_rent_investment_property_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_deposit_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_deposit_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_litigation_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_litigation_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_litigation_margin_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_litigation_margin_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_other_receivable_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_other_receivable_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_reverse_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_reverse_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_equity_investment_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_equity_investment_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_interest_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_interest_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_bill_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_bill_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_collateral_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_collateral_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_financial_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_financial_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_buying_back_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_buying_back_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_bond_ac_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_bond_ac_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_financial_fvoci_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_financial_fvoci_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_bank_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_bank_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_trust_ac_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_trust_ac_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_other_asset_ac_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_other_asset_ac_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_other_financial_ac_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_other_financial_ac_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_gov_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_gov_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_other_long_receivables_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_other_long_receivables_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_other_long_related_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_other_long_related_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_borrowings_interest_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_borrowings_interest_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_investment_property_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_investment_property_amount numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_other_balance numeric(20, 2) NULL DEFAULT 0,
       depreciation_loss_other_amount numeric(20, 2) NULL DEFAULT 0,
       publication_fee_balance numeric(20, 2) NULL DEFAULT 0,
       publication_fee_amount numeric(20, 2) NULL DEFAULT 0,
       receive_sum_debt_restructure_balance numeric(20, 2) NULL DEFAULT 0,
       receive_sum_debt_restructure_amount numeric(20, 2) NULL DEFAULT 0,
       unrealized_revenue_debt_restructure_balance numeric(20, 2) NULL DEFAULT 0,
       unrealized_revenue_debt_restructure_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_outtax_debt_restructure_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_outtax_debt_restructure_amount numeric(20, 2) NULL DEFAULT 0,
       unrealized_revenue_other_debt_restructure_balance numeric(20, 2) NULL DEFAULT 0,
       unrealized_revenue_other_debt_restructure_amount numeric(20, 2) NULL DEFAULT 0,
       collect_payment_balance numeric(20, 2) NULL DEFAULT 0,
       collect_payment_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_default_interest_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_default_interest_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_terminate_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_terminate_amount numeric(20, 2) NULL DEFAULT 0,
       litigation_virtual_balance numeric(20, 2) NULL DEFAULT 0,
       litigation_virtual_amount numeric(20, 2) NULL DEFAULT 0,
       period_code int4 NOT NULL,
       eas_voucher_id varchar(50) NULL,
       bill_contract_code varchar(60) NULL,
       receivable_other_revenue_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_other_revenue_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_damages_revenue_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_damages_revenue_amount numeric(20, 2) NULL DEFAULT 0,
       continue_involving_assets_balance numeric(20, 2) NULL DEFAULT 0,
       continue_involving_assets_amount numeric(20, 2) NULL DEFAULT 0,
       payable_margin_entrusted_loans_balance numeric(20, 2) NULL DEFAULT 0,
       payable_margin_entrusted_loans_amount numeric(20, 2) NULL DEFAULT 0,
       continue_involving_debts_balance numeric(20, 2) NULL DEFAULT 0,
       continue_involving_debts_amount numeric(20, 2) NULL DEFAULT 0,
       debt_restructuring_income_balance numeric(20, 2) NULL DEFAULT 0,
       debt_restructuring_income_amount numeric(20, 2) NULL DEFAULT 0,
       lease_transfer_income_balance numeric(20, 2) NULL DEFAULT 0,
       lease_transfer_income_amount numeric(20, 2) NULL DEFAULT 0,
       other_business_cost_balance numeric(20, 2) NULL DEFAULT 0,
       other_business_cost_amount numeric(20, 2) NULL DEFAULT 0,
       financial_institution_fee_balance numeric(20, 2) NULL DEFAULT 0,
       financial_institution_fee_amount numeric(20, 2) NULL DEFAULT 0,
       payable_bill_balance numeric(20, 2) NULL DEFAULT 0,
       payable_bill_amount numeric(20, 2) NULL DEFAULT 0,
       receivable_bill_balance numeric(20, 2) NULL DEFAULT 0,
       receivable_bill_amount numeric(20, 2) NULL DEFAULT 0,
       CONSTRAINT eg_contract_balance_month_partition_pk PRIMARY KEY (id)
);
CREATE INDEX eg_contract_balance_month_business_date_idx ON financialdb.eg_contract_balance_month USING btree (business_date);
CREATE INDEX eg_contract_balance_month_eas_voucher_id_idx ON financialdb.eg_contract_balance_month USING btree (eas_voucher_id);
CREATE INDEX eg_contract_balance_month_partition_business_code_idx ON financialdb.eg_contract_balance_month USING btree (business_code);
CREATE INDEX eg_contract_balance_month_partition_client_code_idx ON financialdb.eg_contract_balance_month USING btree (client_code);
CREATE INDEX eg_contract_balance_month_partition_org_id_idx ON financialdb.eg_contract_balance_month USING btree (org_id);
CREATE INDEX eg_contract_balance_month_partition_period_code_idx ON financialdb.eg_contract_balance_month USING btree (period_code);
CREATE INDEX eg_contract_balance_month_partition_voucher_date_idx ON financialdb.eg_contract_balance_month USING btree (voucher_date);
CREATE INDEX eg_contract_balance_month_partition_voucher_id_idx ON financialdb.eg_contract_balance_month USING btree (voucher_id);
CREATE INDEX idx_eg_contract_balance_month_partition_index_id ON financialdb.eg_contract_balance_month USING btree (contract_code);

-- Table Triggers

create trigger eg_contract_balance_month_trigger before
    insert
    on
financialdb.eg_contract_balance_month for each row execute function auto_insert_into_tbl_month_partition('period_code');



CREATE TABLE financialdb.eg_eas_exchange_rate (
      id int8 NOT NULL,
      execute_date varchar(100) NULL,
      source_eas_code varchar(100) NULL,
      source_eas_name varchar(100) NULL,
      target_eas_code varchar(100) NULL,
      target_eas_name varchar(100) NULL,
      exchange_rate numeric(28, 10) NULL,
      create_by varchar(32) NULL,
      create_time timestamp NULL,
      update_by varchar(32) NULL,
      update_time timestamp NULL,
      del_flag bpchar(1) NULL DEFAULT '0'::bpchar,
      CONSTRAINT eg_eas_exchange_rate_pkey PRIMARY KEY (id)
);
CREATE INDEX eg_eas_exchange_rate_execute_date_idx ON financialdb.eg_eas_exchange_rate USING btree (execute_date);



ALTER TABLE financialdb.eg_receive_tax RENAME COLUMN org_id TO seller_name;
ALTER TABLE financialdb.eg_receive_tax RENAME COLUMN invoice_accrual_name TO product_name;