ThreadPool.xxlCoreSize=2
ThreadPool.xxlMaxSize=4
ThreadPool.queueCapacity=100
ThreadPool.aliveSec=60
xxl.job.admin.addresses=
xxl.job.accessToken=
xxl.job.executor.appname=financehub-engine-service
xxl.job.executor.address=http://127.0.0.1:9998/
xxl.job.executor.port=9998
xxl.job.executor.logpath=D:/projects/financehub-dev/financehub-dev/logs/xxl-job/engine
xxl.job.executor.logretentiondays=7
xxl.job.executor.jobGroup=0
eas.service.login.url=http://127.0.0.1
eas.service.login.user=local
eas.service.login.password=local
eas.service.login.slnName=eas
eas.service.login.dcName=HX001
eas.service.login.language=L2
eas.service.login.dbType=1
eas.service.addVoucher.url=http://127.0.0.1
eas.service.addVoucher.system=CWZT
eas.service.addVoucher.type=ImportVoucherImpl
eas.service.easLogin.url=http://127.0.0.1
attachment.tenantCode=local
attachment.secret.slug=local
attachment.secret.app-key=local
attachment.secret.app-secret=local
attachment.url.baseURL=http://127.0.0.1
attachment.url.get-token=/token
attachment.url.get-file=/file
attachment.url.get-file-info=/file-info
attachment.url.download-file=/download
attachment.url.upload-file=/upload
attachment.url.preview-file=/preview
attachment.url.online-edit-file=/online-edit
attachment.url.delete-file=/delete
attachment.url.move-file=/move
attachment.url.delivery-file=/delivery
attachment.url.rename-file=/rename
attachment.url.create-folder=/create-folder
hthx.org.url=http://127.0.0.1
hthx.org.tenant-code=local
hthx.org.tenant-secret=local
external.interface.fund-org-claim-ebank=http://127.0.0.1
file.storage.basicpath.windows=D:/projects/financehub-dev/financehub-dev/logs/tmp
file.storage.basicpath.linux=D:/projects/financehub-dev/financehub-dev/logs/tmp
file.storage.easLoginePath.windows=D:/projects/financehub-dev/financehub-dev/logs/tmp
file.storage.easLoginePath.linux=D:/projects/financehub-dev/financehub-dev/logs/tmp
service.parth=D:/projects/financehub-dev/financehub-dev/code/financehub-engine/financehub-engine-service/target/classes/LtpaToken.properties
serviceFeeAllocationStart=2024-01-01
unapportionsDate=2024-01-01
approve.url.verification-url=/verification
approve.url.assetAbsRedeem-url=/assetAbsRedeem
approve.url.assetAbsTransferPayment-url=/assetAbsTransferPayment
approve.url.chargeOff-url=/chargeOff
approve.url.contractHis-url=/contractHis
approve.url.convert-transfer-contract-fee-url=/convertTransferContractFee
approve.url.convert-transfer-third-part-payment-url=/convertTransferThirdPartPayment
approve.url.convert-transfer-third-part-url=/convertTransferThirdPart
approve.url.convert-transfer-url=/convertTransfer
approve.url.costCategory-url=/costCategory
approve.url.courtCost-url=/courtCost
approve.url.discounted-transfer-internal-url=/discountedTransferInternal
approve.url.impairmentProvision-url=/impairmentProvision
approve.url.internalTransfer-url=/internalTransfer
approve.url.leaseIncome-url=/measurementEngine/incomeProvisionDetail?leaseIncomeId=
approve.url.longIncomeConfirm-url=/longIncomeConfirm
approve.url.longReceivableRegister-url=/longReceivableRegister
approve.url.manual-url=/manual
approve.url.marginContract-url=/marginContract
approve.url.nonConfirmAccount-url=/nonConfirmAccount
approve.url.offlineContract-url=/offlineContract
approve.url.parityTransfer-url=/parityTransfer
approve.url.payVat-url=/payVat
approve.url.payableInsurance-url=/payableInsurance
approve.url.recyclingEquipIn-url=/recyclingEquipIn
approve.url.recyclingEquipOut-url=/recyclingEquipOut
approve.url.rentIncomeConfirm-url=/rentIncomeConfirm
approve.url.rentRegister-url=/rentRegister
approve.url.sellRegister-url=/sellRegister
approve.url.serviceFee-url=/serviceFee
approve.url.specialContract-url=/specialContract
approve.url.taOtherPayable-url=/taOtherPayable
approve.url.taReclassification-url=/taReclassification
approve.url.tailAdjust-url=/tailAdjust
approve.url.transferRegister-url=/transferRegister
spring.rabbitmq.listener.simple.missing-queues-fatal=false
spring.rabbitmq.listener.direct.missing-queues-fatal=false
mybatis-plus.mapper-locations=classpath*:mapper/**/*.xml,classpath*:com/**/mapper/xml/*.xml
